package us.shandian.giga.get

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import org.schabi.newpipe.extractor.streamdata.format.MediaFormat
import org.schabi.newpipe.extractor.streamdata.stream.AudioStream
import org.schabi.newpipe.extractor.streamdata.stream.Stream
import org.schabi.newpipe.extractor.streamdata.stream.SubtitleStream
import org.schabi.newpipe.extractor.streamdata.stream.VideoStream
import org.schabi.newpipe.util.StreamTypeUtil
import org.schabi.newpipe.util.VideoQualityStringifier
import java.io.Serializable

@Parcelize
class MissionRecoveryInfo<M : MediaFormat>(
    var format: M, // TODO
    var desired: String? = null,
    var isDesired2: Boolean = false,
    var desiredBitrate: Int = 0,
    var kind: Char = Char.MIN_VALUE,
    var validateCondition: String? = null
) : Serializable, Parcelable {
    constructor(stream: Stream<M>) : this(format = stream.mediaFormat()) {
        when (stream) {
            is AudioStream -> {
                desiredBitrate = stream.averageBitrate()
                isDesired2 = false
                kind = 'a'
            }
            is VideoStream -> {
                desired = VideoQualityStringifier.toString(stream.qualityData())
                isDesired2 = StreamTypeUtil.isVideoOnly(stream)
                kind = 'v'
            }
            is SubtitleStream -> {
                desired = stream.languageCode()
                isDesired2 = stream.autoGenerated()
                kind = 's'
            }
            else -> throw RuntimeException("Unknown stream kind")
        }
    }

    override fun toString(): String {
        val info: String
        val str = StringBuilder()
        str.append("{type=")
        when (kind) {
            'a' -> {
                str.append("audio")
                info = "bitrate=$desiredBitrate"
            }
            'v' -> {
                str.append("video")
                info = "quality=$desired videoOnly=$isDesired2"
            }
            's' -> {
                str.append("subtitles")
                info = "language=$desired autoGenerated=$isDesired2"
            }
            else -> {
                info = ""
                str.append("other")
            }
        }
        str.append(" format=")
            .append(format.name())
            .append(' ')
            .append(info)
            .append('}')
        return str.toString()
    }
}
